export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
export const CLEAN_LOGIN_FORM = 'CLEAN_LOGIN_FORM';
export const FETCH_LOGIN_REQUESTED = 'FETCH_LOGIN_REQUESTED';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILED = 'FETCH_LOGIN_FAILED';
export const FETCH_SESSION_REQUESTED = 'FETCH_SESSION_REQUESTED';
export const SET_REQUEST_FLAG = 'SET_REQUEST_FLAG';
export const FETCH_PASSWORD_RECOVERY_REQUESTED = 'FETCH_PASSWORD_RECOVERY_REQUESTED';
export const SET_SESSION_PROFILE_IMAGE = 'SET_SESSION_PROFILE_IMAGE';
export const SET_STATUS_MESSAGE = 'SET_STATUS_MESSAGE';
export const SET_MODAL_DATA = 'SET_MODAL_DATA';

export const SUBMIT_RECOVERY_PASSWORD_REQUESTED = 'SUBMIT_RECOVERY_PASSWORD_REQUESTED';
export const SUBMIT_RECOVERY_PASSWORD_SUCCEEDED = 'SUBMIT_RECOVERY_PASSWORD_SUCCEEDED';

export const SUBMIT_VERIFY_TOKEN_REQUESTED = 'SUBMIT_VERIFY_TOKEN_REQUESTED';
export const SUBMIT_VERIFY_TOKEN_SUCCEEDED = 'SUBMIT_VERIFY_TOKEN_SUCCEEDED';

export const SUBMIT_CONFIRM_PASSWORD_RESET_REQUESTED = 'SUBMIT_CONFIRM_PASSWORD_RESET_REQUESTED';
export const SUBMIT_CONFIRM_PASSWORD_RESET_SUCCEEDED = 'SUBMIT_CONFIRM_PASSWORD_RESET_SUCCEEDED';

export const SUBMIT_PERSON_ACTIVATE_REQUESTED = 'SUBMIT_PERSON_ACTIVATE_REQUESTED';
export const SUBMIT_PERSON_ACTIVATE_SUCCEEDED = 'SUBMIT_PERSON_ACTIVATE_SUCCEEDED';

export const SESSION_LOADING = 'SESSION_LOADING';
export const UPDATE_GLOBAL_MODAL = 'UPDATE_GLOBAL_MODAL';
export const SET_IS_MOBILE = 'SET_IS_MOBILE';
